import type { Product, Category } from '@/types'

export const categories: Category[] = [
  {
    id: '1',
    name: 'Men',
    slug: 'men',
    description: 'Discover our curated collection of men\'s fashion',
    image: 'https://images.pexels.com/photos/1619802/pexels-photo-1619802.jpeg?auto=compress&cs=tinysrgb&w=800',
    parent_id: null,
  },
  {
    id: '2',
    name: 'Women',
    slug: 'women',
    description: 'Elegant and sophisticated women\'s fashion',
    image: 'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=800',
    parent_id: null,
  },
  {
    id: '3',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Complete your look with our premium accessories',
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
    parent_id: null,
  },
  {
    id: '4',
    name: 'Shoes',
    slug: 'shoes',
    description: 'Premium footwear for every occasion',
    image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
    parent_id: null,
  },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Elegant Cashmere Coat',
    slug: 'elegant-cashmere-coat',
    description: 'Luxurious cashmere coat with impeccable tailoring. Features a double-breasted design, notched lapels, and a belted waist for a sophisticated silhouette. Perfect for both formal occasions and everyday elegance.',
    price: 1299,
    compare_at_price: 1599,
    images: [
      'https://images.pexels.com/photos/1539364/pexels-photo-1539364.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1539364/pexels-photo-1539364.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '2',
    category: categories[1],
    colors: [
      { id: 'c1', name: 'Black', hex: '#0a0a0a' },
      { id: 'c2', name: 'Camel', hex: '#c19a6b' },
      { id: 'c3', name: 'Ivory', hex: '#fffff0' },
    ],
    sizes: [
      { id: 's1', name: 'XS', stock: 5 },
      { id: 's2', name: 'S', stock: 12 },
      { id: 's3', name: 'M', stock: 8 },
      { id: 's4', name: 'L', stock: 6 },
      { id: 's5', name: 'XL', stock: 3 },
    ],
    tags: ['outerwear', 'winter', 'luxury', 'cashmere'],
    featured: true,
    new_arrival: true,
    best_seller: true,
    limited_edition: false,
    stock: 34,
    rating: 4.9,
    reviews_count: 128,
    created_at: '2024-01-15',
    updated_at: '2024-01-15',
  },
  {
    id: '2',
    name: 'Premium Leather Jacket',
    slug: 'premium-leather-jacket',
    description: 'Handcrafted from the finest Italian leather, this jacket exudes timeless cool. Features asymmetrical zipper, snap-down lapels, and quilted lining for ultimate comfort and style.',
    price: 899,
    compare_at_price: null,
    images: [
      'https://images.pexels.com/photos/10409204/pexels-photo-10409204.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '1',
    category: categories[0],
    colors: [
      { id: 'c4', name: 'Black', hex: '#0a0a0a' },
      { id: 'c5', name: 'Brown', hex: '#5c4033' },
    ],
    sizes: [
      { id: 's6', name: 'S', stock: 8 },
      { id: 's7', name: 'M', stock: 15 },
      { id: 's8', name: 'L', stock: 10 },
      { id: 's9', name: 'XL', stock: 7 },
    ],
    tags: ['outerwear', 'leather', 'motorcycle'],
    featured: true,
    new_arrival: false,
    best_seller: true,
    limited_edition: false,
    stock: 40,
    rating: 4.8,
    reviews_count: 256,
    created_at: '2024-01-10',
    updated_at: '2024-01-10',
  },
  {
    id: '3',
    name: 'Silk Evening Gown',
    slug: 'silk-evening-gown',
    description: 'Stunning floor-length silk gown designed for special occasions. Features a draped bodice, open back, and flowing train. The perfect statement piece for galas and formal events.',
    price: 2199,
    compare_at_price: 2499,
    images: [
      'https://images.pexels.com/photos/1642225/pexels-photo-1642225.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '2',
    category: categories[1],
    colors: [
      { id: 'c6', name: 'Emerald', hex: '#50c878' },
      { id: 'c7', name: 'Burgundy', hex: '#722f37' },
      { id: 'c8', name: 'Navy', hex: '#000080' },
    ],
    sizes: [
      { id: 's10', name: 'XS', stock: 3 },
      { id: 's11', name: 'S', stock: 5 },
      { id: 's12', name: 'M', stock: 8 },
      { id: 's13', name: 'L', stock: 4 },
    ],
    tags: ['formal', 'evening', 'silk', 'special-occasion'],
    featured: true,
    new_arrival: true,
    best_seller: false,
    limited_edition: true,
    stock: 20,
    rating: 5.0,
    reviews_count: 42,
    created_at: '2024-01-20',
    updated_at: '2024-01-20',
  },
  {
    id: '4',
    name: 'Italian Wool Blazer',
    slug: 'italian-wool-blazer',
    description: 'Expertly tailored blazer crafted from premium Italian wool. Features a slim fit, notch lapels, and functional button cuffs. A versatile piece that transitions from office to evening effortlessly.',
    price: 699,
    compare_at_price: 849,
    images: [
      'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '1',
    category: categories[0],
    colors: [
      { id: 'c9', name: 'Charcoal', hex: '#36454f' },
      { id: 'c10', name: 'Navy', hex: '#000080' },
      { id: 'c11', name: 'Tan', hex: '#d2b48c' },
    ],
    sizes: [
      { id: 's14', name: 'S', stock: 10 },
      { id: 's15', name: 'M', stock: 18 },
      { id: 's16', name: 'L', stock: 12 },
      { id: 's17', name: 'XL', stock: 6 },
      { id: 's18', name: 'XXL', stock: 4 },
    ],
    tags: ['blazer', 'formal', 'wool', 'tailored'],
    featured: true,
    new_arrival: false,
    best_seller: true,
    limited_edition: false,
    stock: 50,
    rating: 4.7,
    reviews_count: 312,
    created_at: '2024-01-05',
    updated_at: '2024-01-05',
  },
  {
    id: '5',
    name: 'Premium Sneakers',
    slug: 'premium-sneakers',
    description: 'Luxury sneakers combining Italian craftsmanship with contemporary design. Made from premium leather with a cushioned sole for all-day comfort. A perfect blend of style and functionality.',
    price: 399,
    compare_at_price: null,
    images: [
      'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '4',
    category: categories[3],
    colors: [
      { id: 'c12', name: 'White', hex: '#ffffff' },
      { id: 'c13', name: 'Black', hex: '#0a0a0a' },
      { id: 'c14', name: 'Gray', hex: '#808080' },
    ],
    sizes: [
      { id: 's19', name: '7', stock: 8 },
      { id: 's20', name: '8', stock: 12 },
      { id: 's21', name: '9', stock: 15 },
      { id: 's22', name: '10', stock: 18 },
      { id: 's23', name: '11', stock: 10 },
      { id: 's24', name: '12', stock: 6 },
    ],
    tags: ['shoes', 'sneakers', 'casual', 'leather'],
    featured: true,
    new_arrival: true,
    best_seller: true,
    limited_edition: false,
    stock: 69,
    rating: 4.9,
    reviews_count: 489,
    created_at: '2024-01-18',
    updated_at: '2024-01-18',
  },
  {
    id: '6',
    name: 'Designer Sunglasses',
    slug: 'designer-sunglasses',
    description: 'Handcrafted sunglasses with polarized lenses and titanium frames. Offers superior UV protection with effortless style. Each pair comes with a premium leather case.',
    price: 349,
    compare_at_price: 449,
    images: [
      'https://images.pexels.com/photos/701880/pexels-photo-701880.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '3',
    category: categories[2],
    colors: [
      { id: 'c15', name: 'Black/Gold', hex: '#0a0a0a' },
      { id: 'c16', name: 'Tortoise', hex: '#8b4513' },
      { id: 'c17', name: 'Crystal', hex: '#e8e8e8' },
    ],
    sizes: [
      { id: 's25', name: 'One Size', stock: 25 },
    ],
    tags: ['accessories', 'sunglasses', 'titanium'],
    featured: false,
    new_arrival: true,
    best_seller: false,
    limited_edition: false,
    stock: 25,
    rating: 4.6,
    reviews_count: 87,
    created_at: '2024-01-22',
    updated_at: '2024-01-22',
  },
  {
    id: '7',
    name: 'Luxury Watch',
    slug: 'luxury-watch',
    description: 'Swiss-made automatic timepiece with sapphire crystal and 100m water resistance. Features a stainless steel bracelet and exhibition caseback. A true statement of refinement.',
    price: 2999,
    compare_at_price: null,
    images: [
      'https://images.pexels.com/photos/273671/pexels-photo-273671.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '3',
    category: categories[2],
    colors: [
      { id: 'c18', name: 'Silver', hex: '#c0c0c0' },
      { id: 'c19', name: 'Rose Gold', hex: '#b76e79' },
      { id: 'c20', name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { id: 's26', name: '42mm', stock: 8 },
      { id: 's27', name: '44mm', stock: 12 },
      { id: 's28', name: '46mm', stock: 5 },
    ],
    tags: ['accessories', 'watch', 'swiss', 'automatic'],
    featured: true,
    new_arrival: false,
    best_seller: true,
    limited_edition: true,
    stock: 25,
    rating: 5.0,
    reviews_count: 156,
    created_at: '2024-01-08',
    updated_at: '2024-01-08',
  },
  {
    id: '8',
    name: 'Cashmere Sweater',
    slug: 'cashmere-sweater',
    description: 'Ultra-soft cashmere sweater with a relaxed fit. Features ribbed trim and a classic crew neck design. Perfect for layering or wearing on its own.',
    price: 449,
    compare_at_price: 549,
    images: [
      'https://images.pexels.com/photos/7691175/pexels-photo-7691175.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '2',
    category: categories[1],
    colors: [
      { id: 'c21', name: 'Cream', hex: '#fffdd0' },
      { id: 'c22', name: 'Gray', hex: '#808080' },
      { id: 'c23', name: 'Navy', hex: '#000080' },
      { id: 'c24', name: 'Camel', hex: '#c19a6b' },
    ],
    sizes: [
      { id: 's29', name: 'XS', stock: 4 },
      { id: 's30', name: 'S', stock: 8 },
      { id: 's31', name: 'M', stock: 12 },
      { id: 's32', name: 'L', stock: 6 },
      { id: 's33', name: 'XL', stock: 3 },
    ],
    tags: ['sweater', 'cashmere', 'knitwear'],
    featured: false,
    new_arrival: false,
    best_seller: true,
    limited_edition: false,
    stock: 33,
    rating: 4.8,
    reviews_count: 234,
    created_at: '2024-01-12',
    updated_at: '2024-01-12',
  },
  {
    id: '9',
    name: 'Tailored Dress Pants',
    slug: 'tailored-dress-pants',
    description: 'Impeccably tailored dress pants crafted from fine wool blend. Features a slim fit, flat front, and unfinished hem for custom tailoring. The foundation of any refined outfit.',
    price: 279,
    compare_at_price: null,
    images: [
      'https://images.pexels.com/photos/1596200/pexels-photo-1596200.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '1',
    category: categories[0],
    colors: [
      { id: 'c25', name: 'Charcoal', hex: '#36454f' },
      { id: 'c26', name: 'Navy', hex: '#000080' },
      { id: 'c27', name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { id: 's34', name: '28', stock: 5 },
      { id: 's35', name: '30', stock: 8 },
      { id: 's36', name: '32', stock: 12 },
      { id: 's37', name: '34', stock: 10 },
      { id: 's38', name: '36', stock: 6 },
    ],
    tags: ['pants', 'formal', 'tailored', 'wool'],
    featured: false,
    new_arrival: false,
    best_seller: false,
    limited_edition: false,
    stock: 41,
    rating: 4.5,
    reviews_count: 167,
    created_at: '2024-01-14',
    updated_at: '2024-01-14',
  },
  {
    id: '10',
    name: 'Designer Handbag',
    slug: 'designer-handbag',
    description: 'Exquisite handcrafted leather handbag with gold-tone hardware. Features multiple compartments and adjustable shoulder strap. The perfect everyday companion for the modern woman.',
    price: 1499,
    compare_at_price: 1799,
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '3',
    category: categories[2],
    colors: [
      { id: 'c28', name: 'Black', hex: '#0a0a0a' },
      { id: 'c29', name: 'Tan', hex: '#d2b48c' },
      { id: 'c30', name: 'Burgundy', hex: '#722f37' },
    ],
    sizes: [
      { id: 's39', name: 'One Size', stock: 15 },
    ],
    tags: ['bag', 'accessories', 'leather', 'luxury'],
    featured: true,
    new_arrival: true,
    best_seller: true,
    limited_edition: true,
    stock: 15,
    rating: 4.9,
    reviews_count: 98,
    created_at: '2024-01-25',
    updated_at: '2024-01-25',
  },
  {
    id: '11',
    name: 'Merino Wool Turtleneck',
    slug: 'merino-wool-turtleneck',
    description: 'Luxuriously soft merino wool turtleneck with a slim fit. Naturally temperature-regulating for year-round comfort. A timeless essential for any wardrobe.',
    price: 189,
    compare_at_price: 249,
    images: [
      'https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '1',
    category: categories[0],
    colors: [
      { id: 'c31', name: 'Charcoal', hex: '#36454f' },
      { id: 'c32', name: 'Camel', hex: '#c19a6b' },
      { id: 'c33', name: 'Black', hex: '#0a0a0a' },
    ],
    sizes: [
      { id: 's40', name: 'S', stock: 12 },
      { id: 's41', name: 'M', stock: 18 },
      { id: 's42', name: 'L', stock: 14 },
      { id: 's43', name: 'XL', stock: 8 },
    ],
    tags: ['sweater', 'turtleneck', 'merino', 'winter'],
    featured: false,
    new_arrival: false,
    best_seller: true,
    limited_edition: false,
    stock: 52,
    rating: 4.7,
    reviews_count: 278,
    created_at: '2024-01-03',
    updated_at: '2024-01-03',
  },
  {
    id: '12',
    name: 'High-Heel Strappy Sandals',
    slug: 'high-heel-strappy-sandals',
    description: 'Elegant strappy sandals with a stiletto heel and cushioned footbed. Handcrafted from premium leather with adjustable buckle strap. Perfect for evening occasions.',
    price: 329,
    compare_at_price: null,
    images: [
      'https://images.pexels.com/photos/2849742/pexels-photo-2849742.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category_id: '4',
    category: categories[3],
    colors: [
      { id: 'c34', name: 'Black', hex: '#0a0a0a' },
      { id: 'c35', name: 'Nude', hex: '#e3bc77' },
      { id: 'c36', name: 'Gold', hex: '#ffd700' },
    ],
    sizes: [
      { id: 's44', name: '5', stock: 4 },
      { id: 's45', name: '6', stock: 6 },
      { id: 's46', name: '7', stock: 8 },
      { id: 's47', name: '8', stock: 10 },
      { id: 's48', name: '9', stock: 5 },
    ],
    tags: ['shoes', 'heels', 'sandals', 'evening'],
    featured: false,
    new_arrival: true,
    best_seller: false,
    limited_edition: false,
    stock: 33,
    rating: 4.6,
    reviews_count: 145,
    created_at: '2024-01-19',
    updated_at: '2024-01-19',
  },
]

export const featuredProducts = products.filter(p => p.featured)
export const newArrivals = products.filter(p => p.new_arrival)
export const bestSellers = products.filter(p => p.best_seller)
export const limitedEdition = products.filter(p => p.limited_edition)
